services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5000:8080"
    volumes:
      - ./sources/Web.Core:/src/sources/Web.Core:ro
    labels:
      - "com.microsoft.visual-studio.project-name=Web.Core"