<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>23387361-8569-47a2-867f-a5adeea8562d</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="appsettings.Docker.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.Docker.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="MySql.Data" Version="9.6.0" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Quartz.AspNetCore" Version="3.15.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data.Accessor\Data.Accessor.csproj" />
    <ProjectReference Include="..\Data.Database\Data.Database.csproj" />
    <ProjectReference Include="..\Logic.Import\Logic.Import.csproj" />
    <ProjectReference Include="..\Logic.Shared\Logic.Shared.csproj" />
    <ProjectReference Include="..\Logic.UserService\Logic.UserService.csproj" />
    <ProjectReference Include="..\Service.Api\Service.Api.csproj" />
  </ItemGroup>

</Project>
